### ISSUE TITLE
Add dependency for exposing a CLI

### ISSUE THREAD

**Issue by ewolfe** [ewolfe/retina-resizer-app#2]
https://github.com/clap-rs/clap seems like it will work

**Comment by harpe116** [comment]
Looks like the leading CLI parser for Rust.

**Comment by ewolfe** [comment]
We don't probably need this just yet.

**Comment by ewolfe** [comment]
Definitely not needed anymore, per https://github.com/ewolfe/retina-resizer-app/pull/4#issuecomment-472082578
